--  users.sql

create table if not exists users (
    id serial primary key,
     name character varying(20),
  password character varying(32),
  ip character varying(15),
  state character varying(20),
  login_time character varying(20),
  logout_time character varying(20),
  cer_flag character varying(20),
  cer_no character varying(20),
  cer_name character varying(20),
  cer_crm character varying(10),
  cer_photo integer,
  mail_flag character varying(20),
  email character varying(100),
  phone_flag character varying(20),
  phone character varying(20),
  call_falg character varying(20),
  call_no character varying(20),
  ip_flag character varying(20),
  ip_no character varying(20),
  vip_flag character varying(20),
  reg_time character varying(20),
  session_id character varying(20),
  org character varying(200),
  reg_ip character varying(20),
  reg_ie character varying(200),
  active_time character varying(20)
)